# 应用
app:
  port: 3000

# 数据库
db:
  default: "mysql"
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "root"
    database: "qdev"

# 存储
storage:
  default: "local"
  local:
  oss:
  cos:
# 第三方登录
# 微信
# 小程序
# 存储

