# 应用
app:
  port: 3000

# 数据库
db:
  default: "mysql"
  mysql:
    host: "localhost"
    port: 3006
    username: "root"
    password: "root"
    database: "qdev"
# 三方
thrid:
  qq:
    app_key:
    app_secret:
    callback:
  weixin:
    app_key:
    app_secret:
    callback:
  sina:
    app_key:
    app_secret:
    callback:
  dingtalk:
    app_key:
    app_secret:
    callback:
  
# 存储
storage:
  default: "local"
  local:
  oss:
  cos:
# 第三方登录
# 微信
# 小程序
# 存储

